apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
    color: blue  # This is how you switch between blue or green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
